spring.application.name=FormPI2025
server.servlet.context-path=/FormPI2025
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB
server.servlet.session.timeout=30m

# Ubicación de archivos estáticos
spring.web.resources.static-locations=classpath:/static/,file:/imagenes/formularios/

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:D:/data/biblioteca.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA/Hibernate Configuration
# USA SOLO ESTA PROPIEDAD DEL DIALECTO PARA PROBAR:
spring.jpa.properties.hibernate.dialect=com.enigmabridge.hibernate.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update # Sé cauteloso con 'update' en producción
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG