spring.application.name=FormPI2025
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB
server.servlet.session.timeout=30m
server.servlet.context-path=/FormPI2025
spring.web.resources.static-locations=file:/imagenes/formularios/