spring.application.name=Generaciones
server.servlet.context-path=/Generaciones
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB
server.servlet.session.timeout=30m

# Ubicacion de archivos estaticos
spring.web.resources.static-locations=classpath:/static/,file:/imagenes/formularios/,file:/logs/premios/



# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/pruebas
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
